/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment1;

import java.util.Scanner;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  /**
   * Returns a nice greeting message.
   *
   * @return the greeing message.
   */
  public String getGreeting() {
    return "Hello World!!!";
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    System.out.println(theApp.getGreeting());

    Scanner myScanner = new Scanner(System.in, "utf-8");

    //Time t1 = new Time();
    //t1.timeConverter(myScanner);

    //Nine t2 = new Nine();
    //t2.hitNine(myScanner);

    //DangerousWork t3 = new DangerousWork();
    //t3.dangerousWork(myScanner);

    //Diamonds t4 = new Diamonds();
    //t4.diamonds(myScanner);

    //GameSrp t5 = new GameSrp();
    //t5.gameSrp(myScanner);

    //DayOfWeek t6 = new DayOfWeek();
    //t6.dayOfWeek(myScanner);

    //Ants t7 = new Ants();
    //t7.theAnt(myScanner);

    //Hex2Dec t8 = new Hex2Dec();
    //t8.hex2Dec(myScanner);

    //PrintCalendar t9 = new PrintCalendar();
    //t9.printCalender(myScanner);
  
    myScanner.close();
  }
}
